config/routes.rb
Represent::Application.routes.draw do
  resources :teammates

  resources :example_scaffolds
  resources :contacts

  get "about/index"
  get "community/index"
  get "services/expertise"
  get "services/design"
  get "services/development"
  get "services/mobile"
  get "services/training"
  get "services/mobile"
  get "services/how_we_work"
  get "portfolio/index"
  resources :projects

  get "blog/index"
  get "welcome/index"
  get '/blog', to: 'blog#index'
  get '/portfolio', to: 'portfolio#index'
  get '/contact', to: "contacts#new"
  get '/services', to: "services#index"
  get '/community', to: "community#index"
  get '/about', to: "about#index"
  
  resources :posts

  root 'welcome#index'

  

end

app/models/project.rb
class Project < ActiveRecord::Base
  # validates :title, presence: true

  # attr_accessible :title, :body, :image_url, :pubdate

  # Carrierwave uploader
  mount_uploader :image, ImageUploader

  attr_accessor :portfolio

  def self.most_recent(limit=21)
    order(pubdate: :desc).limit(limit)
  end

  def self.open_source(limit=4)
    order(pubdate: :desc).where(:is_open_source => true).limit(limit)
  end
  
  def picture?
    image_url.present?
  end

  def publish(clock=DateTime)
    return false unless valid?
    self.pubdate = clock.now
    @portfolio.add_undertaking(self)
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy]

  # GET /projects
  # GET /projects.json
  def index
    @projects = Project.all
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
    @project = Project.find(params[:id])
    
  end

  # GET /projects/new
  def new
    @project = @portfolio.new_project
  end

  # # GET /projects/1/edit
  # def edit
  # end

  # POST /projects
  # POST /projects.json
  def create
    @project = @portfolio.new_project(project_params)    
    # @project = @portfolio.new_project(params.require(:project).permit(:title, :body, :image_url))
    
    respond_to do |format|
      if @project.publish
        format.html { redirect_to portfolio_path, notice: 'Project was successfully created.' }
        # format.json { render action: 'show', status: :created, location: @project }
      else
        format.html { render action: 'new' }
        # format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end


  # def create
  #   @post = @blog.new_post(params.require(:post).permit(:title, :body, :image_url))
  #   if @post.publish
  #     redirect_to root_url,
  #           tadah: "Post successfully created"
  #   else
  #     flash.now[:error] = "Whoops, the highlighted fields need better input."
  #     render action: "new"
  #   end
  # end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.require(:project).permit(:title, :body, :logo_url, :image, :remote_image_url, :challenge, 
        :result, :quote, :quotable_person, :quotable_positon_and_company, :one_line_project_description, 
        :summary_image_url, :category, :pubdate)
    end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_client_bar_with_heading.html.erb
<h2 class="section-title">
<strong>Clients</strong> From Startups to Giants</h2>

<div id="client_bar" class="main clearfix">
	<%# list of clients and links to portfolio projects %>
  <ul class="visible-desktop">
<li>AARP</li>
    <li>Accenture</li>
    <li>Agilysys</li>
    <!-- <li><a href="/portfolio/web/amazon-mechanical-turk">Amazon</a></li> -->
    <li>ACS</li>
    <li>Avascent</li>
    <li>Bank of America</li>
    <li><a href="/portfolio/web/betterfly">Betterfly</a></li>
    <li>Bureau of Labor Statistics</li>
  </ul>
  <ul class="visible-desktop">
	<li>Comcast</li>
    <li>comScore</li>
    <li>Cisco</li>
    <li>Citi</li>
    <!-- <li><a href="/portfolio/web/earth-aid">Earth Aid</a></li> -->
    <li>Gannett</li>
    <li>Geico</li>
    <li>Gulfstream</li>
    <!-- <li><a href="/portfolio/web/homezada">HomeZada</a></li> -->
  </ul>
  <ul class="visible-desktop">
	<li>HowAboutWe</li>
    <li>JPMorgan Chase</li>
    <li>Mandiant</li>
    <li>McKinsey &amp; Company</li>
    <!-- <li><a href="/portfolio/mobile/mashable#">Mashable</a></li> -->
    <li>Merck</li>
    <li>MerrilLynch</li>
    <!-- <li><a href="/portfolio/web/the-meeting-board">Meeting Board</a></li> -->
    <!-- <li><a href="/portfolio/mobile/mitsubishi-electric">Mitsubishi Electric</a></li> -->
  </ul>
  <ul class="visible-desktop">
	<!-- <li><a href="/portfolio/mobile/oracle">Oracle</a></li> -->
    <li>Pew Research Center</li>
    <li>Pharm MD</li>
    <li>PPR</li>
    <li>Razoo</li>
    <li>Retail Benefits</li>
    <li>Safeway</li>
    <li>Schlumberger</li>
    <!-- <li><a href="/portfolio/web/scalr">Scalr</a></li> -->
  </ul>
  <ul class="visible-desktop last">
	<li>SGIS</li>
    <li>Sequoia Capital</li>
    <!-- <li><a href="/portfolio/web/socialcode">SocialCode</a></li> -->
    <li>Studio PMG</li>
    <li>Verizon</li>
    <li>Voice of America</li>
    <!-- <li><a href="/portfolio/web/watchparty">WatchParty</a></li> -->
    <li>Whitepages.com</li>
    <li>Visual CV</li>
  </ul>
  <ul class="hidden-desktop first">
	<li>AARP</li>
    <li>Accenture</li>
    <!-- <li><a href="/portfolio/web/amazon-mechanical-turk">Amazon</a></li> -->
    <li>ACS</li>
    <li>Avascent</li>
    <li>Bank of America</li>
    <!-- <li><a href="/portfolio/web/betterfly">Betterfly</a></li>  -->
  	<li>Bureau of Labor Statistics</li>
    <li>Comcast</li>
    <li>Cisco</li>
    <li>Citi</li>
    <li>DubMeNow</li>
    <!-- <li><a href="/portfolio/web/earth-aid">Earth Aid</a></li> -->
    <li>ForumOne</li>
    <li>Gannett</li>
  </ul>
  <ul class="hidden-desktop">
	<li>Geico</li>
   	<li>Gulfstream</li>
    <!-- <li><a href="/portfolio/web/homezada">HomeZada</a></li> -->
    <li>HowAboutWe</li>
    <li>JPMorgan Chase</li>
    <li>Mandiant</li>
    <li>McKinsey &amp;<br> Company</li>
    <!-- <li><a href="/portfolio/mobile/mashable#">Mashable</a></li> -->
    <li>Merck</li>
    <li>MerrilLynch</li>
    <!-- <li><a href="/portfolio/web/the-meeting-board">Meeting Board</a></li> -->
    <!-- <li><a href="/portfolio/mobile/mitsubishi-electric">Mitsubishi Electric</a></li> -->
    <!-- <li><a href="/portfolio/mobile/oracle">Oracle</a></li> -->
    <li>Pew Research Center</li>
    <li>Pharm MD</li>
  </ul>
  <ul class="hidden-desktop last">
	<li>PPR</li>
    <li>Razoo</li>
    <li>Recnation</li>
  	<li>Retail Benefits</li>
    <li>Safeway</li>
    <!-- <li><a href="/portfolio/web/scalr">Scalr</a></li> -->
    <li>Schlumberger</li>
    <li>SGIS</li>
    <li>Sequoia Capital</li>
    <!-- <li><a href="/portfolio/web/socialcode">SocialCode</a></li> -->
    <li>Studio PMG</li>
    <li>Verizon</li>
    <li>Voice of America</li>
    <!-- <li><a href="/portfolio/web/watchparty">WatchParty</a></li> -->
    <li>Whitepages.com</li>
    <li>Visual CV</li>
	<%= link_to "Get in Touch", contact_new_path, :class  => "btn blue small visible-tablet" %>
    <!-- <a href="/contact" class="btn blue small visible-tablet">Get in Touch</a> -->
  </ul>
</div>

app/views/projects/_desktop_info_column.html.erb
<!-- desktop info column-->
<div class="span-1 alpha visible-desktop">

	<%= image_tag @project.logo_url, :title => "Small" %>
	<h3 class="proj-desc"><%= @project.one_line_project_description %></h3>
	<dl class="proj-meta">
	  
		<dt>Challenge</dt>
		<dd><%= @project.challenge %></dd>
		
		<dt>Result</dt>
		<dd><%= @project.result %></dd>
	</dl>

		<blockquote><%= @project.quote %>
<br>
<br>
<em><%= @project.quotable_person %>, <%= @project.quotable_positon_and_company %></em>
		</blockquote>

	<a href="https://github.com/intridea/omniauth" class="btn gray block" id="git-omni"><img alt="Github" src="/assets/github-861739c5bf5c1f1104e9b8d26e4b676e.png"></a>

</div>

app/views/projects/_desktop_phone_image_description.html.erb
<!-- desktop/phone image/description-->
<div class="span-2 omega hidden-tablet">
	<div class="port-photo">
		<%= image_tag @project.main_image_url, :title => "Medium", :width => "578" %>
		
	</div>

	<div class="visible-phone case-study-title">
			<h2><%= desktop_phone_image_description.title %></h2>
			<h3 class="proj-desc"><%= desktop_phone_image_description.one_line_project_description %></h3>
	</div>

	<div class="hidden-tablet case-study-description">
	  <p><%= desktop_phone_image_description.body %></p>

	</div>

</div>

app/views/projects/_form.html.erb
<%= form_for(@project) do |f| %>
  <% if @project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% @project.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </div>
  <div class="field">
    <%= f.label :logo_url %><br>
    <%= f.text_field :logo_url %>
  </div>
  <div class="field">
	  <%=label :image, "Upload Picture:" %>
	  <%= f.file_field :image %><br />
	    <%= f.text_field :remote_image_url, :placeholder  => "http://example.org/king_lear.jpg", :size => "66" %>
	
  </div>
  <div class="field">
    <%= f.label :main_image_url %><br>
    <%= f.text_field :main_image_url %>
  </div>
  <div class="field">
    <%= f.label :challenge %><br>
    <%= f.text_area :challenge %>
  </div>
  <div class="field">
    <%= f.label :result %><br>
    <%= f.text_area :result %>
  </div>
  <div class="field">
    <%= f.label :quote %><br>
    <%= f.text_field :quote %>
  </div>
  <div class="field">
    <%= f.label :quotable_person %><br>
    <%= f.text_field :quotable_person %>
  </div>
  <div class="field">
    <%= f.label :quotable_positon_and_company %><br>
    <%= f.text_field :quotable_positon_and_company %>
  </div>
  <div class="field">
    <%= f.label :one_line_project_description %><br>
    <%= f.text_field :one_line_project_description %>
  </div>
  <div class="field">
    <%= f.label :summary_image_url %><br>
    <%= f.text_field :summary_image_url %>
  </div>
  <div class="field">
    <%= f.label :category %><br>
    <%= f.text_field :category %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/projects/_phone_service.html.erb
<!-- phone service -->
<section id="service-home" class="visible-phone clearfix"><h2 class="section-title">
	<strong>Services</strong> Beautiful Software Solutions</h2>
	<div class="sidebar clearfix">
		<ul>
			<li class="design">
				<a href="/services/design">
					<%= image_tag "icon_user_interface_design_2x.png", :title => "Icon_user_interface_design_2x", :class => "icn-services" %>
				</a>
				<p class="longer">User Interface Design</p>
			</li>
			<li class="rails">
				<a href="/services/development">
					<%= image_tag "icon_ror_development_2x.png", :title => "Icon_ror_development_2x", :class => "icn-services" %>
				</a>
				<p>Ruby on Rails Development</p>
			</li>
			<li class="mobile">
				<a href="/services/mobile">
					<%= image_tag "icon_mobile_app_development_2x.png", :title => "Icon_mobile_app_development_2x", :class => "icn-services" %>
				</a>
				<p>Mobile App Development</p>
			</li>
			<li class="training">
	  			<a href="/training">
					<%= image_tag "icon_ror_training_2x.png", :title => "Icon_ror_training_2x", :class => "icn-services" %>
				</a>
				<p>Ruby on Rails Training</p>
			</li>
		</ul>
		<h3>We build custom web and mobile applications</h3>
		<div id="content">
			<p class="hidden-phone">To compete in this disruptive business world 
you need a serious edge. Great applications give you that edge. At 
<%= @guest_setting.title %>, we work with companies around the world to create custom 
software solutions that are both beautiful <em>and</em> robust, giving companies the edge they need to thrive in any industry. </p>
			<a href="/services" class="btn blue small visible-desktop">Learn More</a>
		</div>			
	</div>
	    </section>

app/views/projects/_project_summary.html.erb
<li class="element  <%= project_summary.category %>">
  <a href="/projects/<%= project_summary.id %>" gt-evt="click" gt-cat="portfolio" gt-act="clients#click" gt-lbl="gallery">
	<%= image_tag project_summary.image_url, :title => "Large" %>
	<h4>
      <strong><%= project_summary.title %></strong> <%= project_summary.one_line_project_description %>
    </h4>
  </a>
</li>

app/views/projects/_project_summary_old.html.erb
<li class="element  mobile">
  <a href="/projects/<%= project_summary.id %>" gt-evt="click" gt-cat="portfolio" gt-act="clients#click" gt-lbl="gallery">
	<%= link_to (image_tag("large_010.png", :title => "Large")), model_path(@project) %>
	<%# image_tag "large_010.png", :title => "Large" %>
	<h4>
      <strong><%= project.title %></strong> <%= project.slogan %>
    </h4>
  </a>
</li>


<h1>Listing projects</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Body</th>
      <th>Logo url</th>
      <th>Image url</th>
      <th>Challenge</th>
      <th>Result</th>
      <th>Quote</th>
      <th>Quotable person</th>
      <th>Quotable positon and company</th>
      <th>One line project description</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @projects.each do |project| %>
      <tr>
        <td><%= project.title %></td>
        <td><%= project.body %></td>
        <td><%= project.logo_url %></td>
        <td><%= project.image_url %></td>
        <td><%= project.challenge %></td>
        <td><%= project.result %></td>
        <td><%= project.quote %></td>
        <td><%= project.quotable_person %></td>
        <td><%= project.quotable_positon_and_company %></td>
        <td><%= project.one_line_project_description %></td>
        <td><%= link_to 'Show', project %></td>
        <td><%= link_to 'Edit', edit_project_path(project) %></td>
        <td><%= link_to 'Destroy', project, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Project', new_project_path %>

app/views/projects/_sub_nav.html.erb
	<div id="sub_nav" class="portfolio_nav">
  
	  <ul class="visible-desktop nav clearfix">
		    <li><a id="link_all" value="all" href="/portfolio/">Show All</a></li>
		    <li><a id="link_web" value="web" href="/portfolio/#web">Web</a></li>
		    <li><a id="link_mobile" value="mobile" href="/portfolio/#mobile">Mobile</a></li>
		    <li><a id="link_labs" value="labs" href="/portfolio/#labs">Labs</a></li>
	  </ul>


	  <div class="visible-tablet styled-select">
	      <select id="selP8I" class="chzn_select tablet_subnav portfolio_filter_main chzn-done" style="width: 160px; display: none;"> 
	          <option selected="selected"><%= sub_nav.title %></option>
	          <option value="all" data-filter="*">Show All</option>
	    		<option value="web">Web</option>
	    		<option value="mobile">Mobile</option>
	    		<option value="labs">Labs</option>						
		  </select>
			<div style="width: 160px;" class="chzn-container chzn-container-single" id="selP8I_chzn">
				<a href="javascript:void(0)" class="chzn-single">
					<span><%= sub_nav.title %></span>
					<div>
						<b></b>
					</div>
				</a>
				<div class="chzn-drop" style="left: -9000px; width: 160px; top: 0px;">
					<div style="" class="chzn-search">
						<input style="width: 125px;" autocomplete="off" type="text">
					</div>
					<ul class="chzn-results">
						<li id="selP8I_chzn_o_0" class="active-result result-selected" style=""><%= sub_nav.title %></li>
						<li id="selP8I_chzn_o_1" class="active-result" style="">Show All</li>
						<li id="selP8I_chzn_o_2" class="active-result" style="">Web</li>
						<li id="selP8I_chzn_o_3" class="active-result" style="">Mobile</li>
						<li id="selP8I_chzn_o_4" class="active-result" style="">Labs</li>
					</ul>
				</div>
			</div>
	    	<div style="display:none">
	    	  <li><a id="link_all" value="all" href="/portfolio/">Show All</a></li>
	    	  <li><a id="link_web" value="web" href="/portfolio/#web">Web</a></li>
	    	  <li><a id="link_mobile" value="mobile" href="/portfolio/#mobile">Mobile</a></li>
	    	  <li><a id="link_labs" value="labs" href="/portfolio/#labs">Labs</a></li>
	      	</div>
	  </div>
  
    </div>

app/views/projects/_tablet_image_description.html.erb
<!-- tablet image/description-->
<div class="span-3 omega visible-tablet">
	<div class="port-photo">
		<%= image_tag "http://fpoimg.com/578x391?text=port-photo+visible-tablet+it", :title => "Medium" %>
		
	</div>

	<div class="visible-desktop case-study-description">
	  <p><%= @project.body %></p>

	</div>
	

app/views/projects/_tablet_info_column.html.erb
<!-- tablet info column -->
<div class="visible-tablet tablet-port">

	<div class="description">
		<span class="meta-logo">
			<%= image_tag "http://fpoimg.com/279x62?text=logo_url+it", :title => "Small" %>
			
		</span>
		<h3 class="proj-desc"><%= tablet_info_column.one_line_project_description %></h3>
		<p><%= tablet_info_column.body %></p>

	</div>
	<div class="span-1">

		<dl class="proj-meta">

			<dt>Challenge</dt>
			<dd><%= tablet_info_column.challenge %></dd>

			<dt>Result</dt>
			<dd><%= tablet_info_column.result %></dd>
		</dl>	  		
	</div>
</div>

app/views/projects/edit.html.erb
<h1>Editing project</h1>

<%= render 'form' %>

<%= link_to 'Show', @project %> |
<%= link_to 'Back', portfolio_path %>

app/views/projects/index.html.erb
<%# render :partial => 'project_summary' %>
          

<div id="content" class="main portfolio clearfix ">
	<div id="sub_nav" class="portfolio_nav">
  
  <ul class="visible-desktop nav clearfix">
<li class="active nav_all"><a value="all" href="#" data-filter="*" class="filter all">Show All</a></li>
	    <li class="nav_web"><a value="web" href="#" data-filter=".web" class="filter web">Web</a></li>
	    <li class="nav_mobile"><a value="mobile" href="#" data-filter=".mobile" class="filter mobile">Mobile</a></li>
	    <li class="nav_labs"><a value="labs" href="#" data-filter=".labs" class="filter labs">Labs</a></li>
  </ul>
<div class="visible-tablet styled-select">
      <select id="selN34" class="chzn_select tablet_subnav portfolio_filter chzn-done" style="width: 160px; display: none;"><option value="all" data-filter="*" selected="selected">Show All</option>
<option value="web" data-filter=".web">Web</option>
<option value="mobile" data-filter=".mobile">Mobile</option>
<option value="labs" data-filter=".labs">Labs</option></select><div style="width: 160px;" class="chzn-container chzn-container-single" id="selN34_chzn"><a href="javascript:void(0)" class="chzn-single"><span>Show All</span><div><b></b></div></a><div class="chzn-drop" style="left: -9000px; width: 160px; top: 0px;"><div style="" class="chzn-search"><input style="width: 125px;" autocomplete="off" type="text"></div><ul class="chzn-results"><li id="selN34_chzn_o_0" class="active-result result-selected" style="">Show All</li><li id="selN34_chzn_o_1" class="active-result" style="">Web</li><li id="selN34_chzn_o_2" class="active-result" style="">Mobile</li><li id="selN34_chzn_o_3" class="active-result" style="">Labs</li></ul></div></div>
</div>
  
  </div>
    <ul class="card_gallery clearfix">
		<%= render :partial => "project_summary", :collection => @projects %>
  </ul>
</div>


<div class="clearfix">
	<div class="hidden-phone">
		<h2 class="section-title">
			<strong>Services</strong> Beautiful Software Solutions</h2>
			<div class="main sidebar full service-tablet clearfix">
				<div class="portfolio_item"> 
  					<h3><a href="/services/design">Web &amp; Mobile Design</a></h3>
					<h4 class="visible-desktop">Research, Analysis and Usable Design</h4>
					<div class="tablet-icn">
						<a href="/services/design">
							<%= image_tag "icon_user_interface_design_2x.png", :title => "Icon_user_interface_design_2x", :class => "icn-services" %>
						</a>
					</div>
					<p class="service-desc">Your customers interact with 
								hundreds of brands every day. 
								Yet, only a few of these 
						interactions are memorable. This is why the experience they share with 
						your brand is so important. An average user experience will yield 
						average results. Give them a 
						memorable one, though, and you’ll have a customer for life. 
					</p>
				</div>
	
				<div class="portfolio_item">
					<h3><a href="/services/development">Web Development</a></h3>
					<h4 class="visible-desktop">Rails, Backbone.js, Node.js</h4>
					<div class="tablet-icn">
						<a href="/services/development">
							<%= image_tag "icon_ror_development_2x.png", :title => "Icon_ror_development_2x", :class => "icn-services" %>
						</a>
					</div>
					<p class="service-desc">Exceptional development on the web is done 
						with cutting-edge technologies like Ruby on Rails.  We stand at the frontier of web 
						design and development, leveraging the benefits of a framework for rapid 
						application development. 
					</p>
				</div>
	
				<div class="portfolio_item omega clearfix">
					<h3><a href="/services/mobile">Mobile Development</a></h3>
					<h4 class="visible-desktop">iOS - iPhone &amp; iPad, Android</h4>
					<div class="tablet-icn mobile">
						<a href="/services/mobile">
							<%= image_tag "icon_mobile_app_development_2x.png", :title => "Icon_mobile_app_development_2x", :class => "icn-services" %>				
						</a>
					</div>
					<p class="service-desc">Smart companies realize the value in being 
						where their customers are. Today, that place is the mobile web. As your 
						customer's expectations grow, your absence becomes even more likely to 
						be filled by your competitors. We'll help you reach your customers with 
						elegant and intuitive mobile applications.
					</p>
				</div>
			</div>
		</div>
		<%= render :partial => 'phone_service' %>
		<%= render :partial => 'client_bar_with_heading' %>

</div>

app/views/projects/new.html.erb
<%# render 'form' %>

<%# link_to 'Back', projects_path %>

<!-- <h1>New Project</h1> -->
<%# form_for @project do |f| %>
	<%# f.text_field :title %>
	<%# f.text_area :body %>
	<%# f.submit %>
<%# end %>
<!-- one_line_project_description -->
<h1>New project</h1>

<%= render 'form' %>