config/routes.rb
Represent::Application.routes.draw do
  resources :teammates

  resources :example_scaffolds
  resources :contacts

  get "about/index"
  get "community/index"
  get "services/expertise"
  get "services/design"
  get "services/development"
  get "services/mobile"
  get "services/training"
  get "services/mobile"
  get "services/how_we_work"
  get "portfolio/index"
  resources :projects

  get "blog/index"
  get "welcome/index"
  get '/blog', to: 'blog#index'
  get '/portfolio', to: 'portfolio#index'
  get '/contact', to: "contacts#new"
  get '/services', to: "services#index"
  get '/community', to: "community#index"
  get '/about', to: "about#index"
  
  resources :posts

  root 'welcome#index'

  

end

app/models/blog.rb
class Blog
  attr_reader :entries
  attr_writer :post_maker
  # attr_accessible :post_maker, :entries
  
  def initialize(entry_fetcher=Post.public_method(:most_recent))
    @entry_fetcher = entry_fetcher
  end

  def title
    "Watching Paint Dry"
  end

  def subtitle
    "The trusted source for drying paint news & opinion"
  end

  def entries
    fetch_entries
  end

  def new_post(*args)
    post_maker.call(*args).tap do |p|
      p.blog = self
    end
  end

  def add_entry(entry)
    entry.save
  end

  private

  def fetch_entries
    @entry_fetcher.()
  end

  def post_maker
    @post_maker ||= Post.public_method(:new)
  end
end

app/models/contact.rb
class Contact < ActiveRecord::Base
end

app/models/guest_setting.rb
class GuestSetting
  def title
    "Second Star Labs"
  end
  
   def email
     "info@secondstarlabs.com"
   end
   
   def phone
      ""
   end
   
   def twitter
    "secondstarlabs"
   end
   
   def street
    "328 Gateway Dr. #116"
   end
   
   def city
    "Pacifica"
   end
   
   def state
    "CA"
   end
   
   def zip
    "94044"
   end
   
   def facebook
    ""
   end
   
   def linkedin
    ""
   end
   
   def feedburner_id
    "secondstarlabs"
   end
   
   def github_id
    "secondstar"
   end
   
   def url
    "secondstarlabs.com"
   end
end

app/models/portfolio.rb
class Portfolio
  attr_reader :undertakings
  attr_writer :project_maker
  
  def initialize(undertaking_fetcher=Project.public_method(:most_recent))
    @undertaking_fetcher = undertaking_fetcher
  end

  def title
    "Watching Paint Dry"
  end

  def subtitle
    "The trusted source for drying paint news & opinion"
  end

  def undertakings
    fetch_undertakings
  end

  def new_project(*args)
    project_maker.call(*args).tap do |p|
      p.portfolio = self
    end
  end

  def add_undertaking(undertaking)
    undertaking.save
  end

  private

  def fetch_undertakings
    @undertaking_fetcher.()
  end

  def project_maker
    @project_maker ||= Project.public_method(:new)
  end
end

app/models/post.rb
class Post < ActiveRecord::Base
include ActiveModel::Validations
validates :title, presence: true

belongs_to :teammate
# Carrierwave uploader
mount_uploader :image, ImageUploader


  # composed_of :tags, :class_name => 'TagList', mapping: %w(tags, tags),
  #                     :converter => ->(value) { TagList(value) }  

  # serialize :tags
  attr_accessor :blog
  # serialize   :tags
  

  def self.most_recent(limit=10)
    order(pubdate: :desc).limit(limit)
  end
  
  def picture?
    image_url.present?
  end

  def publish(clock=DateTime)
    return false unless valid?
    self.pubdate = clock.now
    self.teammmate_id = Teammate.first.id.to_i
    @blog.add_entry(self)
  end
end

app/models/project.rb
class Project < ActiveRecord::Base
  # validates :title, presence: true

  # attr_accessible :title, :body, :image_url, :pubdate

  # Carrierwave uploader
  mount_uploader :image, ImageUploader

  attr_accessor :portfolio

  def self.most_recent(limit=21)
    order(pubdate: :desc).limit(limit)
  end

  def self.open_source(limit=4)
    order(pubdate: :desc).where(:is_open_source => true).limit(limit)
  end
  
  def picture?
    image_url.present?
  end

  def publish(clock=DateTime)
    return false unless valid?
    self.pubdate = clock.now
    @portfolio.add_undertaking(self)
  end
end

app/models/tag_list.rb
require "forwardable"
module Conversions
  private
  def Taglist(value)
    return value if value.is_a?(Taglist)
    Taglist.new(value)
  end
end

class TagList
  extend Forwardable
  include Enumerable
  attr_reader :tags
  
  def_delegators :tags, :empty?, :to_a, :each
  
  def initialize(tags)
    case tags
    when Array
      @tags = tags
    else
      @tags = @tags.to_s.split(/\W+/)
    end
    @tags.uniq!
    @tags.each(&:downcase!)
  end
  
  def to_s
    tags.join(", ")
  end
  
  def to_ary
    @tags
  end
  
  def +(other)
    self.class.new(to_a + other.to_a)
  end
  
  def ==(other)
    to_a == Array(other)
  end
  
  def alphabetical
    self.class.new(tags.sort)
  end
end

app/models/teammate.rb
class Teammate < ActiveRecord::Base
  has_many :posts
  
  mount_uploader :image, ImageUploader
  attr_accessor :blog
  
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index
  end
end

app/controllers/blog_controller.rb
class BlogController < ApplicationController
  def index
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def new
    @post = @blog.new_post
  end
  
  # GET /post/1
  # GET /post/1.json
  def show
    @post = Post.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @post }
    end
  end
  
  def create
    @post = @blog.new_post(post_params)

    if @post.publish
      flash.now[:warning] = "Entry added."
      flash.now[:notice] = "Entry added."
      redirect_to post_url(@post), tadah: "Pay attention to the road"
    else
      flash.now[:error] = "Whoops, the highlighted fields need better input."
      render action: "new"
    end
  end
  
  private
    def post_params
      params.require(:post).permit(:title, :body, :image, :remote_image_url)
    end
  
end

app/controllers/teammates_controller.rb
class TeammatesController < ApplicationController
  before_action :set_teammate, only: [:show, :edit, :update, :destroy]

  # GET /teammates
  # GET /teammates.json
  def index
    @teammates = Teammate.all
  end

  # GET /teammates/1
  # GET /teammates/1.json
  def show
  end

  # GET /teammates/new
  def new
    @teammate = Teammate.new
  end

  # GET /teammates/1/edit
  def edit
  end

  # POST /teammates
  # POST /teammates.json
  def create
    @teammate = Teammate.new(teammate_params)

    respond_to do |format|
      if @teammate.save
        format.html { redirect_to @teammate, notice: 'Teammate was successfully created.' }
        format.json { render action: 'show', status: :created, location: @teammate }
      else
        format.html { render action: 'new' }
        format.json { render json: @teammate.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /teammates/1
  # PATCH/PUT /teammates/1.json
  def update
    respond_to do |format|
      if @teammate.update(teammate_params)
        format.html { redirect_to @teammate, notice: 'Teammate was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @teammate.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /teammates/1
  # DELETE /teammates/1.json
  def destroy
    @teammate.destroy
    respond_to do |format|
      format.html { redirect_to teammates_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_teammate
      @teammate = Teammate.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def teammate_params
      params.require(:teammate).permit(:first_name, :last_name, :biography, :image)
    end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blog_helper.rb
module BlogHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/community_helper.rb
module CommunityHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/portfolio_helper.rb
module PortfolioHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/helpers/teammates_helper.rb
module TeammatesHelper
end

app/views/teammates/_form.html.erb
<%= form_for @teammate, html: { multipart: true }  do |f| %>
  <% if @teammate.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@teammate.errors.count, "error") %> prohibited this teammate from being saved:</h2>

      <ul>
      <% @teammate.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :first_name %><br>
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br>
    <%= f.text_field :last_name %>
  </div>
  
  <div class="field">
  
	<%= f.file_field :image %><br />
	<%= f.text_field :image_url, :placeholder  => "http://example.org/mugshot.jpg", :size => "66" %>
  </div>
  <div class="field">
    <%= f.label :biography %><br>
    <%= f.text_area :biography %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/teammates/edit.html.erb
<h1>Editing teammate</h1>

<%= render 'form' %>

<%= link_to 'Show', @teammate %> |
<%= link_to 'Back', teammates_path %>

app/views/teammates/index.html.erb
<h1>Listing teammates</h1>

<table>
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Biography</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @teammates.each do |teammate| %>
      <tr>
        <td><%= teammate.first_name %></td>
        <td><%= teammate.last_name %></td>
        <td><%= teammate.biography %></td>
        <td><%= teammate.image_url %></td>
        <td><%= link_to 'Show', teammate %></td>
        <td><%= link_to 'Edit', edit_teammate_path(teammate) %></td>
        <td><%= link_to 'Destroy', teammate, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Teammate', new_teammate_path %>

app/views/teammates/new.html.erb
<h1>New teammate</h1>

<%= render 'form' %>

<%= link_to 'Back', teammates_path %>

app/views/teammates/show.html.erb
<p id="notice"><%= notice %></p>

<p>
	<strong>Mugshot</strong><br />
	<%= image_tag @teammate.image_url.to_s, :width => '100' %>
</p>
<p>
  <strong>First name:</strong>
  <%= @teammate.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @teammate.last_name %>
</p>

<p>
  <strong>Biography:</strong>
  <%= @teammate.biography %>
</p>

<%= link_to 'Edit', edit_teammate_path(@teammate) %> |
<%= link_to 'Back', teammates_path %>