config/routes.rb
Represent::Application.routes.draw do
  resources :teammates

  resources :example_scaffolds
  resources :contacts

  get "about/index"
  get "community/index"
  get "services/expertise"
  get "services/design"
  get "services/development"
  get "services/mobile"
  get "services/training"
  get "services/mobile"
  get "services/how_we_work"
  get "portfolio/index"
  resources :projects

  get "blog/index"
  get "welcome/index"
  get '/blog', to: 'blog#index'
  get '/portfolio', to: 'portfolio#index'
  get '/contact', to: "contacts#new"
  get '/services', to: "services#index"
  get '/community', to: "community#index"
  get '/about', to: "about#index"
  
  resources :posts

  root 'welcome#index'

  

end

app/models/blog.rb
class Blog
  attr_reader :entries
  attr_writer :post_maker
  # attr_accessible :post_maker, :entries
  
  def initialize(entry_fetcher=Post.public_method(:most_recent))
    @entry_fetcher = entry_fetcher
  end

  def title
    "Watching Paint Dry"
  end

  def subtitle
    "The trusted source for drying paint news & opinion"
  end

  def entries
    fetch_entries
  end

  def new_post(*args)
    post_maker.call(*args).tap do |p|
      p.blog = self
    end
  end

  def add_entry(entry)
    entry.save
  end

  private

  def fetch_entries
    @entry_fetcher.()
  end

  def post_maker
    @post_maker ||= Post.public_method(:new)
  end
end

app/models/contact.rb
class Contact < ActiveRecord::Base
end

app/models/guest_setting.rb
class GuestSetting
  def title
    "Second Star Labs"
  end
  
   def email
     "info@secondstarlabs.com"
   end
   
   def phone
      ""
   end
   
   def twitter
    "secondstarlabs"
   end
   
   def street
    "328 Gateway Dr. #116"
   end
   
   def city
    "Pacifica"
   end
   
   def state
    "CA"
   end
   
   def zip
    "94044"
   end
   
   def facebook
    ""
   end
   
   def linkedin
    ""
   end
   
   def feedburner_id
    "secondstarlabs"
   end
   
   def github_id
    "secondstar"
   end
   
   def url
    "secondstarlabs.com"
   end
end

app/models/portfolio.rb
class Portfolio
  attr_reader :undertakings
  attr_writer :project_maker
  
  def initialize(undertaking_fetcher=Project.public_method(:most_recent))
    @undertaking_fetcher = undertaking_fetcher
  end

  def title
    "Watching Paint Dry"
  end

  def subtitle
    "The trusted source for drying paint news & opinion"
  end

  def undertakings
    fetch_undertakings
  end

  def new_project(*args)
    project_maker.call(*args).tap do |p|
      p.portfolio = self
    end
  end

  def add_undertaking(undertaking)
    undertaking.save
  end

  private

  def fetch_undertakings
    @undertaking_fetcher.()
  end

  def project_maker
    @project_maker ||= Project.public_method(:new)
  end
end

app/models/post.rb
class Post < ActiveRecord::Base
include ActiveModel::Validations
validates :title, presence: true

belongs_to :teammate
# Carrierwave uploader
mount_uploader :image, ImageUploader


  # composed_of :tags, :class_name => 'TagList', mapping: %w(tags, tags),
  #                     :converter => ->(value) { TagList(value) }  

  # serialize :tags
  attr_accessor :blog
  # serialize   :tags
  

  def self.most_recent(limit=10)
    order(pubdate: :desc).limit(limit)
  end
  
  def picture?
    image_url.present?
  end

  def publish(clock=DateTime)
    return false unless valid?
    self.pubdate = clock.now
    self.teammmate_id = Teammate.first.id.to_i
    @blog.add_entry(self)
  end
end

app/models/project.rb
class Project < ActiveRecord::Base
  # validates :title, presence: true

  # attr_accessible :title, :body, :image_url, :pubdate

  # Carrierwave uploader
  mount_uploader :image, ImageUploader

  attr_accessor :portfolio

  def self.most_recent(limit=21)
    order(pubdate: :desc).limit(limit)
  end

  def self.open_source(limit=4)
    order(pubdate: :desc).where(:is_open_source => true).limit(limit)
  end
  
  def picture?
    image_url.present?
  end

  def publish(clock=DateTime)
    return false unless valid?
    self.pubdate = clock.now
    @portfolio.add_undertaking(self)
  end
end

app/models/tag_list.rb
require "forwardable"
module Conversions
  private
  def Taglist(value)
    return value if value.is_a?(Taglist)
    Taglist.new(value)
  end
end

class TagList
  extend Forwardable
  include Enumerable
  attr_reader :tags
  
  def_delegators :tags, :empty?, :to_a, :each
  
  def initialize(tags)
    case tags
    when Array
      @tags = tags
    else
      @tags = @tags.to_s.split(/\W+/)
    end
    @tags.uniq!
    @tags.each(&:downcase!)
  end
  
  def to_s
    tags.join(", ")
  end
  
  def to_ary
    @tags
  end
  
  def +(other)
    self.class.new(to_a + other.to_a)
  end
  
  def ==(other)
    to_a == Array(other)
  end
  
  def alphabetical
    self.class.new(tags.sort)
  end
end

app/models/teammate.rb
class Teammate < ActiveRecord::Base
  has_many :posts
  
  mount_uploader :image, ImageUploader
  attr_accessor :blog
  
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index
  end
end

app/controllers/blog_controller.rb
class BlogController < ApplicationController
  def index
  end
end

app/controllers/community_controller.rb
class CommunityController < ApplicationController
  def index
    @posts                = Post.most_recent(3)
    @open_source_projects = Project.open_source(4)
  end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blog_helper.rb
module BlogHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/community_helper.rb
module CommunityHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/portfolio_helper.rb
module PortfolioHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/helpers/teammates_helper.rb
module TeammatesHelper
end

app/views/community/_events_2items.html.erb
<h2 class="section-title">
<strong>Events</strong> We stay active</h2>										
<div id="portfolio_bar" class="main clearfix">
        <div class="portfolio_item alpha  ">
	<div class="item_img">
  			    	<a href="http://strataconf.com/strataeu2013/"><img alt="Medium" src="/assets/strata.png"></a>
        			<span class="author-bubble">Nov 11, 2013<span class="arrow"></span></span>
  			</div>
	<div class="item_desc">
		<p></p>
	</div>
  		</div>
        <div class="portfolio_item omega  ">
  			<div class="item_img">
  				<a href="http://thenextweb.com/conference/usa"><img alt="Medium" src="/assets/tnw.png"></a>
        		<span class="author-bubble">Oct 01, 2013<span class="arrow"></span></span>
  			</div>
  			<div class="item_desc">
  			    	<p>Join 1000+ attendees and the finest industry speakers. 
				Discover the latest trends in mobile and web and learn about best 
				business practic...</p>
  			    </div>
  			</div>
</div>

app/views/community/_header_description.html.erb
<div class="header-description clearfix">
	<h2>The Technological Zeitgeist</h2>
	<p>Our love of beautiful code and aesthetic design doesn't end with 
our workday; our love for, and obsession with technology means that we
are experts in our progamming languages and frameworks.</p>
</div>

app/views/community/_open_source.html.erb
<!-- Open Source -->
<h2 class="section-title">
<strong>Open Source Projects</strong> We give back</h2>										
<div id="portfolio_bar" class="main clearfix">
    <div class="portfolio_item alpha ">
  		    	<a href="http://<%= @guest_setting.title %>.github.com/stately/"><img alt="Medium" src="/assets/stately.png"></a>
  		    	<div class="item_desc">
  		    		<h4><strong>Stately</strong></h4>
  		      	<p>A web font for making simple maps using HTML and CSS.</p>
  		    	</div>
  		  	</div>
    <div class="portfolio_item omega ">
  		    	<a href="http://<%= @guest_setting.title %>.github.com/omniauth/"><img alt="Medium" src="/assets/omniauth.png"></a>
  		    	<div class="item_desc">
  		    		<h4><strong>OmniAuth</strong></h4>
  		      	<p>A flexible authentication system utilizing Rack middleware. </p>
  		    	</div>
  		  	</div>
    <div class="portfolio_item alpha marg-norm">
  		    	<a href="http://<%= @guest_setting.title %>.github.com/grape/"><img alt="Medium" src="/assets/grape.png"></a>
  		    	<div class="item_desc">
  		    		<h4><strong>Grape</strong></h4>
  		      	<p>An opinionated micro-framework for creating REST-like APIs in Ruby</p>
  		    	</div>
  		  	</div>
    <div class="portfolio_item omega marg-norm">
  		    	<a href="https://github.com/<%= @guest_setting.title %>/tweetstream"><img alt="Medium" src="/assets/tweetstream.png"></a>
  		    	<div class="item_desc">
  		    		<h4><strong>TweetStream</strong></h4>
  		      	<p>A RubyGem to access the Twitter Streaming API</p>
  		    	</div>
  		  	</div>
</div> 

app/views/community/_open_source_project.html.erb
<div class="portfolio_item omega marg-norm">
		<%= link_to image_tag(open_source_project.logo_url, :title => open_source_project.title), project_path(open_source_project), :width => "248px" %>
		<div class="item_desc">
		<h4><strong><%= open_source_project.title %></strong></h4>
  	<p><%= open_source_project.slogan %></p>
	</div>
</div>

app/views/community/_open_source_projects.html.erb
<!-- Open Source -->
<h2 class="section-title">
<strong>Open Source Projects</strong> We give back</h2>										
<div id="portfolio_bar" class="main clearfix">
    <div class="portfolio_item alpha ">
		<% @first_open_source_project =  Array(@open_source_projects[0])%>
		<% @first_open_source_project.each do |project| %>
			<%= link_to image_tag(project.logo_url, :title => project.title), project_path(project) %>
			<div class="item_desc">
				<h4><strong><%= project.title %></strong></h4>
				<p><%= project.slogan %></p>
			</div>
		<% end %>
			
  	</div>
    <div class="portfolio_item omega ">
		<% @second_open_source_project =  Array(@open_source_projects[1])%>
		<% @second_open_source_project.each do |project| %>
				<%= link_to image_tag(project.logo_url, :title => project.title), project_path(project) %>
			<div class="item_desc">
				<h4><strong><%= project.title %></strong></h4>
				<p><%= project.slogan %></p>
			</div>
		<% end %>
  	</div>
			<%= render :partial => "open_source_project", :collection => @open_source_projects[2..3] %>
</div> 

app/views/community/_open_source_projects_side.html.erb
<h3>Open Source Projects (5)</h3>
<select style="display: none;" 
	class="chzn_select chzn-done" 
	id="oos_project_url" name="oos_project_url">
	<option selected="selected" value="http://<%= @guest_setting.title %>.github.com/stately/">Stately</option>
	<option value="http://<%= @guest_setting.title %>.github.com/omniauth/">OmniAuth</option>
	<option value="http://<%= @guest_setting.title %>.github.com/grape/">Grape</option>
	<option value="https://github.com/<%= @guest_setting.title %>/tweetstream">TweetStream</option>
	<option value="https://github.com/<%= @guest_setting.title %>/multi_json">Multi_json</option>
</select>
<div style="width: 240px;" class="chzn-container chzn-container-single" id="oos_project_url_chzn">
	<a href="javascript:void(0)" class="chzn-single">
		<span>Stately</span>
		<div><b></b></div>
	</a>
	<div class="chzn-drop" style="left: -9000px; width: 240px; top: 37px;">
		<div style="" class="chzn-search"><input style="width: 205px;" autocomplete="off" type="text"></div>
		<ul class="chzn-results">
			<li id="oos_project_url_chzn_o_0" class="active-result result-selected" style="">
				Stately
			</li>
			<li id="oos_project_url_chzn_o_1" class="active-result" style="">OmniAuth</li>
			<li id="oos_project_url_chzn_o_2" class="active-result" style="">Grape</li>
			<li id="oos_project_url_chzn_o_3" class="active-result" style="">TweetStream</li>
			<li id="oos_project_url_chzn_o_4" class="active-result" style="">
				Multi_json
			</li>
		</ul>
	</div>
</div>

app/views/community/_past_events.html.erb
<h3>Past Events</h3>
		<ul class="post-list">
			<li>
  					<h4><a href="http://gogaruco.com/">GoGaRuCo</a></h4>
  					<div class="meta">
  						Join us for two days of in-depth technical expl...
  					</div>
  				</li>
		    <li>
  					<h4><a href="http://www.businessanalyticsstrategiessummit.com/">Business Analytics Strategies Summit</a></h4>
  					<div class="meta">
  						
  					</div>
  				</li>
		    <li>
  					<h4><a href="http://mobileuxcamp.com/">MobileUXCamp DC</a></h4>
  					<div class="meta">
  						MobileUX Camp DC brings together people from th...
  					</div>
  				</li>
		    <li>
  					<h4><a href="http://smashingconf.com/">Smashing Conference 2013</a></h4>
  					<div class="meta">
  						We're sponsoring this event led by Smashing Mag...
  					</div>
  				</li>
		</ul>
		<a href="/community/events" class="btn blue more-event">See More Events</a>

app/views/community/_popular_blog_posts.html.erb
<h3>Popular Blog Posts</h3>
		<ul class="post-list">
			<li>
  					<h4>
<a href="/blog/2013/9/13/see-you-at-mobileux-camp-dc-tomorrow">See You At MobileUXCamp DC Tomorrow!</a> 
				</h4>
  						<div class="meta">
  							by Robert Dempsey | September 13, 2013 
  						</div>
  				</li>
		    <li>
  					<h4>
<a href="/blog/2011/8/18/whats-wrong-with-patents">What's Wrong With Patents? It's Obvious.</a> 
				</h4>
  					<div class="meta">
  						by Michael Bleigh | August 18, 2011 
  					</div>
  				</li>
		    <li>
  					<h4>
					<a href="/blog/2010/4/7/ipad-wallpaper-photoshop-template">
						iPad Wallpaper Template for Photoshop
					</a> 
				</h4>
  					<div class="meta">
  						by Dave Potsiadlo | April  7, 2010 
  					</div>
  				</li>
		    <li>
  					<h4>
					<a href="/blog/2011/5/13/rails3-gems">Rails 3: Fully Loaded</a> 
				</h4>
  					<div class="meta">
  						by Andy Wang | May 13, 2011 
  					</div>
  				</li>
		</ul>

app/views/community/_presentation_slides.html.erb
<h3>Presentation Slides (19)</h3>
<select style="display: none;" class="chzn_select chzn-done" id="slide_url" name="slide_url">
	<option selected="selected" value="http://cl.ly/221H1U193K1x">Tablet as a Utility</option>
	<option value="http://speakerdeck.com/u/<%= @guest_setting.title %>/p/<%= @guest_setting.title %>-modevux">MoDevUX 2012</option>
	<option value="http://www.slideshare.net/mbleigh/omniauth-from-the-ground-up-railsconf-2011">
		OmniAuth: From the Ground Up (RailsConf 2011)
	</option>
	<option value="http://www.slideshare.net/mbleigh/omniauth-from-the-ground-up">
		OmniAuth: From the Ground Up (Red Dirt Ruby Conf 2011)
	</option>
	<option value="http://www.slideshare.net/mbleigh/th-5784985">
		The Grapes of Rapid (Ruby Conf 2010)
	</option>
	<option value="http://www.slideshare.net/mbleigh/upgrading-to-rails-3">
		Upgrading to Rails 3 (OSCON 2010)
	</option>
	<option value="http://www.slideshare.net/mbleigh/interoperable-web-4778065">
		Deciphering the Interoperable Web (Ruby Midwest 2010)
	</option>
	<option value="http://www.slideshare.net/mbleigh/the-present-future-of-oauth">
		The Present Future of OAuth (RailsConf 2010)
	</option>
	<option value="http://www.slideshare.net/mbleigh/nodejs-and-ruby">Node.js and Ruby</option>
	<option value="http://www.slideshare.net/mbleigh/persistence-smoothie-blending-sql-and-nosql-rubynation-edition">
		Persistence Smoothie: Blending SQL and NoSQL (RubyNation 2010)
	</option>
	<option value="http://www.slideshare.net/mbleigh/persistence-smoothie">
		Persistence Smoothie (Confoo 2010, Montreal)
	</option>
	<option value="http://www.slideshare.net/mbleigh/twitter-on-rails-1396030">
		Twitter on Rails (RailsConf 2009)
	</option>
	<option value="http://www.slideshare.net/mbleigh/hacking-the-midend-advanced-rails-ui-techniques-presentation">
		Hacking the Mid-End (RailsConf Europe 2008)
	</option>
	<option value="https://speakerdeck.com/u/jch/p/evented-ruby-vs-nodejs">
		Evented Ruby vs Node.js (RailsConf 2012)
	</option>
	<option value="http://blog.peteonrails.com/?p=253">Intro to Spatial Programming</option>
	<option value="https://speakerdeck.com/u/peteonrails/p/location-matters-rubynation">
		Location Matters (RubyNation 2012)
	</option>
	<option value="http://www.slideshare.net/brendanlim/macruby-to-the-max-3530772">
		MacRuby to the Max
	</option>
	<option value="http://www.slideshare.net/mbleigh/divshot-pitch-deck">Divshot</option>
	<option				
	value="http://www.slideshare.net/skyfallsin/the-big-wave-of-indian-startups-almost-effortless-entrepreneurship-using-ruby">
		The Big Wave of Indian Startups
	</option>
</select>

<div style="width: 240px;" class="chzn-container chzn-container-single" id="slide_url_chzn">
	<a href="javascript:void(0)" class="chzn-single">
			<span>Tablet as a Utility</span>
			<div><b></b></div>
	</a>
	<div class="chzn-drop" style="left: -9000px; width: 240px; top: 37px;">
		<div style="" class="chzn-search">
			<input style="width: 205px;" autocomplete="off" type="text">
		</div>
		<ul class="chzn-results">
			<li id="slide_url_chzn_o_0" class="active-result result-selected" style="">
				Tablet as a Utility
			</li>
			<li id="slide_url_chzn_o_1" class="active-result" style="">MoDevUX 2012</li>
			<li id="slide_url_chzn_o_2" class="active-result" style="">OmniAuth: From the Ground Up (RailsConf 2011)</li>
			<li id="slide_url_chzn_o_3" class="active-result" style="">OmniAuth: From the Ground Up (Red Dirt Ruby Conf 2011)</li>
			<li id="slide_url_chzn_o_4" class="active-result" style="">The Grapes of Rapid (Ruby Conf 2010)</li>
			<li id="slide_url_chzn_o_5" class="active-result" style="">Upgrading to Rails 3 (OSCON 2010)</li>
			<li id="slide_url_chzn_o_6" class="active-result" style="">Deciphering the Interoperable Web (Ruby Midwest 2010)</li>
			<li id="slide_url_chzn_o_7" class="active-result" style="">The Present Future of OAuth (RailsConf 2010)</li>
			<li id="slide_url_chzn_o_8" class="active-result" style="">Node.js and Ruby</li>
			<li id="slide_url_chzn_o_9" class="active-result" style="">Persistence Smoothie: Blending SQL and NoSQL (RubyNation 2010)</li>
			<li id="slide_url_chzn_o_10" class="active-result" style="">Persistence Smoothie (Confoo 2010, Montreal)</li>
			<li id="slide_url_chzn_o_11" class="active-result" style="">Twitter on Rails (RailsConf 2009)</li>
			<li id="slide_url_chzn_o_12" class="active-result" style="">Hacking the Mid-End (RailsConf Europe 2008)</li>
			<li id="slide_url_chzn_o_13" class="active-result" style="">Evented Ruby vs Node.js (RailsConf 2012)</li>
			<li id="slide_url_chzn_o_14" class="active-result" style="">Intro to Spatial Programming</li>
			<li id="slide_url_chzn_o_15" class="active-result" style="">Location Matters (RubyNation 2012)</li>
			<li id="slide_url_chzn_o_16" class="active-result" style="">MacRuby to the Max</li>
			<li id="slide_url_chzn_o_17" class="active-result" style="">Divshot</li>
			<li id="slide_url_chzn_o_18" class="active-result" style="">The Big Wave of Indian Startups</li>
		</ul>
	</div>
</div>

app/views/community/_sponsored_projects.html.erb
<!-- Sponsored Projects -->
<h2 class="section-title">
<strong>Sponsored Projects</strong> We help sustain others</h2>										
<div id="portfolio_bar" class="main clearfix">
    <div class="portfolio_item alpha">
  		    	<a href="http://pry.github.com/"><img alt="Medium" src="/assets/pry.png"></a>
  		    	<div class="item_desc">
  		      		<h4><strong>Pry</strong></h4>
  		      		<p>Pry is a powerful alternative to the standard IRB shell for Ruby.</p>
  		    	</div>
  		  </div>
    <div class="portfolio_item omega">
  		    	<a href="http://foster.ly/"><img alt="Medium" src="/assets/fosterly.png"></a>
  		    	<div class="item_desc">
  		      		<h4><strong>Foster.ly</strong></h4>
  		      		<p>Foster.ly is a community of entrepreneurs in DC, Maryland and Virginia.</p>
  		    	</div>
  		  </div>
</div>

app/views/community/_sub_nav.html.erb
<div id="sub_nav">
  <ul class="visible-desktop nav clearfix">
	<li class="active"><a href="/community"><%= @guest_setting.title %> Community</a></li>
    <li class=""><a href="/community/events">Events</a></li>
    <li class=""><a href="/community/opensource">OSS Projects</a></li>
  </ul>
  <div class="visible-tablet styled-select">
	    <select class="chzn_select tablet_subnav chzn-done" 
			id="community_sub_nav_url" 
			name="community_sub_nav_url" 
			style="width: 160px; display: none;">
			<option value="/community" selected="selected"><%= @guest_setting.title %> Community</option>
			<option value="/community/events">Events</option>
			<option value="/community/opensource">OSS Projects</option>
		</select>
		<div style="width: 160px;" 
			class="chzn-container chzn-container-single" 
			id="community_sub_nav_url_chzn">
			<a href="javascript:void(0)" class="chzn-single">
				<span><%= @guest_setting.title %> Community</span>
				<div><b></b></div>
			</a>
			<div class="chzn-drop" style="left: -9000px; width: 160px; top: 0px;">
				<div style="" class="chzn-search">
					<input style="width: 125px;" autocomplete="off" type="text">
				</div>
				<ul class="chzn-results">
					<li id="community_sub_nav_url_chzn_o_0" 
						class="active-result result-selected" style="">
						<%= @guest_setting.title %> Community
					</li>
					<li id="community_sub_nav_url_chzn_o_1" class="active-result" style="">Events</li>
					<li id="community_sub_nav_url_chzn_o_2" class="active-result" style="">OSS Projects</li>
				</ul>
			</div>
		</div>
  </div>
</div>

app/views/community/index.html.erb
<% content_for :masthead_container do -%>
  community_container
<% end -%>

<div id="flash">
</div>
          
<div class="main sidebar clearfix masthead" data-masthead-image="">
	<%= render :partial => 'sub_nav' %>
	<%= render :partial => 'header_description' %>
</div>

<div class="clearfix">
	<div class="community-wrap clearfix">
		
		<%# render :partial => 'events_2items' %>
		
		<%= render 'open_source_projects' %>
				
	</div>
	<div class="community-side visible-desktop">
		<div class="sidebar clearfix">
			<%# render :partial => 'presentation_slides' %>
			
			<%# render :partial => 'open_source_projects_side' %>

			<%= render :partial => 'popular_blog_posts' %>
			<%= render :partial => 'past_events' %>
			
			<a href="" class="hiring">We're Hiring</a>
		</div>
		<div class="main new-gig clearfix">
			<h3>Looking for a new gig?</h3>
			<p>Obsessed with good code and beautiful design? Do you value form as
 much as function? We do too. And we're looking for people like you.</p>
			<a href="/careers" class="btn green block large">View Open Positions</a>
		</div>
	</div>	

</div>
<%= render :partial => "/shared/blog_3_entries" %>